### ISSUE TITLE
issue, can not load 2 exact drivers.

### ISSUE THREAD

**Issue by gyliso12** [Liverus/Metamorph#3]
i cant load some of the drivers for some reason, this is a metamorph issue since i have turned off my core isolation so that drivers can run fluently on my device, is there a fix for this? im going to provide you with a screenshot.
![Screenshot (102)](https://github.com/Liverus/Metamorph/assets/160538934/a0d65138-4cdd-417b-b99a-1c6a5c020167)

**Comment by Liverus** [comment]
This issue does not come from Metamorph but from kdmapper which fails to map the driver because of Windows 11's new security policies. If you did disable the Microsoft Vulnerable Driver Blocklist and restarted your device, I cannot help you any further as I'm not responsible for this part of the software.

**Comment by 2212187063** [comment]
What should I do if I have this problem in win10
